service: contentforge_1344

image: adam1344/contentforge_1344

deploy_timeout: 120

servers:
  web:
    - 51.75.124.208

proxy:
  ssl: true
  host: contentforge.1344.fr

registry:
  username: adam1344
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL

ssh:
  user: ubuntu
